# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BAD
                                 A QGIS plugin
 BAD_Burned Area Detector
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-01-24
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Thomas Martinoli
        email                : th.martinoli96@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from PyQt5 import QtWidgets


# Initialize Qt resources from file resources.py
from .resources import *
#it is necessary to insert this line in order to make possible the import of data
from qgis.core import QgsProject
# Import the code for the dialog
from .BAD_dialog import BADDialog
import os.path
from .DoMagic import *
from .Error import Ui_Error
import numpy as np
from qgis.utils import iface

class BAD:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'BAD_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Burned Area Detector')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('BAD', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/BAD/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Burned Area Detector'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Burned Area Detector'),
                action)
            self.iface.removeToolBarIcon(action)


###################################################################################################
###################################################################################################
###################################################################################################

#  This part of the script contains the code about the restore buttons that are      
#  present inside the plug-in.                                            
#  In this way the user is able to restore the default value and         
#  the state of each spinbox, checkbox, radiusbox in the related page.  

    # INPUT TAB #
    def reset_input_tab(self):

        # Band reset value
        Bands = [
        self.dlg.spinBox_input_B1,
        self.dlg.spinBox_input_B2,
        self.dlg.spinBox_input_B3,
        self.dlg.spinBox_input_B4,
        self.dlg.spinBox_input_B5,
        self.dlg.spinBox_input_B6,
        self.dlg.spinBox_input_B7,
        self.dlg.spinBox_input_B8,
        self.dlg.spinBox_input_B8A,
        self.dlg.spinBox_input_B9,
        self.dlg.spinBox_input_B10,
        self.dlg.spinBox_input_B11,
        self.dlg.spinBox_input_B12]

        Nband=1
        for Band in Bands:
            Band.setValue(Nband)
            Nband=Nband+1

        # Band reset check
        self.dlg.checkBox_input_B1.setCheckState(False)
        self.dlg.checkBox_input_B2.setCheckState(False)
        self.dlg.checkBox_input_B3.setCheckState(False)
        self.dlg.checkBox_input_B4.setCheckState(False)
        self.dlg.checkBox_input_B5.setCheckState(False)
        self.dlg.checkBox_input_B6.setCheckState(True)
        self.dlg.checkBox_input_B7.setCheckState(True)
        self.dlg.checkBox_input_B8.setCheckState(True)
        self.dlg.checkBox_input_B8A.setCheckState(False)
        self.dlg.checkBox_input_B9.setCheckState(False)
        self.dlg.checkBox_input_B10.setCheckState(False)
        self.dlg.checkBox_input_B11.setCheckState(False)
        self.dlg.checkBox_input_B12.setCheckState(True)

        print("restored input tab")   

###################################################################################################
    
    # FEATURES TAB default #
    def reset_Features_D_tab(self):
        CheckBoxes = [
        self.dlg.checkBox_FD_postB6,
        self.dlg.checkBox_FD_postB7,
        self.dlg.checkBox_FD_postNIR,
        self.dlg.checkBox_FD_deltaB6,
        self.dlg.checkBox_FD_deltaB7,
        self.dlg.checkBox_FD_deltaNIR,
        self.dlg.checkBox_FD_deltaB12]

        # Reset check
        for CKbox in CheckBoxes:
            CKbox.setCheckState(True)

        # Reset value K
        self.dlg.doubleSpinBox_FD_postB6_K.setValue(-125.89400)
        self.dlg.doubleSpinBox_FD_postB7_K.setValue(-115.77500)
        self.dlg.doubleSpinBox_FD_postNIR_K.setValue(-123.65800)
        self.dlg.doubleSpinBox_FD_deltaB6_K.setValue(-120.29100)
        self.dlg.doubleSpinBox_FD_deltaB7_K.setValue(-93.72060)
        self.dlg.doubleSpinBox_FD_deltaNIR_K.setValue(-87.14430)
        self.dlg.doubleSpinBox_FD_deltaB12_K.setValue(236.98400)
        
        # Reset value x
        self.dlg.doubleSpinBox_FD_postB6_x.setValue(0.11090)
        self.dlg.doubleSpinBox_FD_postB7_x.setValue(0.11659)
        self.dlg.doubleSpinBox_FD_postNIR_x.setValue(0.10986)
        self.dlg.doubleSpinBox_FD_deltaB6_x.setValue(-0.05980)
        self.dlg.doubleSpinBox_FD_deltaB7_x.setValue(-0.07527)
        self.dlg.doubleSpinBox_FD_deltaNIR_x.setValue(-0.08657)
        self.dlg.doubleSpinBox_FD_deltaB12_x.setValue(0.04381)

        print("restored Features D tab")  

###################################################################################################

    # FEATURES TAB advanced post #    
    def reset_Features_AP_tab(self):

        CheckBoxes = [
        self.dlg.checkBox_FAP_B1,
        self.dlg.checkBox_FAP_B2,
        self.dlg.checkBox_FAP_B3,
        self.dlg.checkBox_FAP_B4,
        self.dlg.checkBox_FAP_B5,
        self.dlg.checkBox_FAP_B8A,
        self.dlg.checkBox_FAP_B9,
        self.dlg.checkBox_FAP_B10,
        self.dlg.checkBox_FAP_B11,
        self.dlg.checkBox_FAP_B12]

        DoubleSpinBoxes_K = [
        self.dlg.doubleSpinBox_FAP_B1_K,
        self.dlg.doubleSpinBox_FAP_B2_K,
        self.dlg.doubleSpinBox_FAP_B3_K,
        self.dlg.doubleSpinBox_FAP_B4_K,
        self.dlg.doubleSpinBox_FAP_B5_K,
        self.dlg.doubleSpinBox_FAP_B8A_K,
        self.dlg.doubleSpinBox_FAP_B9_K,
        self.dlg.doubleSpinBox_FAP_B10_K,
        self.dlg.doubleSpinBox_FAP_B11_K,
        self.dlg.doubleSpinBox_FAP_B12_K]
        
        DoubleSpinBoxes_x = [
        self.dlg.doubleSpinBox_FAP_B1_x,
        self.dlg.doubleSpinBox_FAP_B2_x,
        self.dlg.doubleSpinBox_FAP_B3_x,
        self.dlg.doubleSpinBox_FAP_B4_x,
        self.dlg.doubleSpinBox_FAP_B5_x,
        self.dlg.doubleSpinBox_FAP_B8A_x,
        self.dlg.doubleSpinBox_FAP_B9_x,
        self.dlg.doubleSpinBox_FAP_B10_x,
        self.dlg.doubleSpinBox_FAP_B11_x,
        self.dlg.doubleSpinBox_FAP_B12_x]

        # Reset value K
        for DSbox in DoubleSpinBoxes_K:
            DSbox.setValue(0)

        # Reset value x
        for DSbox in DoubleSpinBoxes_x:
            DSbox.setValue(0)

        # Reset checkbox
        for CKbox in CheckBoxes:
            CKbox.setCheckState(False)

        print("restored Features AP tab")  
    
###################################################################################################

    # FEATURES TAB advanced delta # 
    def reset_Features_AD_tab(self):
        
        CheckBoxes = [
        self.dlg.checkBox_FAD_B1,
        self.dlg.checkBox_FAD_B2,
        self.dlg.checkBox_FAD_B3,
        self.dlg.checkBox_FAD_B4,
        self.dlg.checkBox_FAD_B5,
        self.dlg.checkBox_FAD_B8A,
        self.dlg.checkBox_FAD_B9,
        self.dlg.checkBox_FAD_B10,
        self.dlg.checkBox_FAD_B11]

        DoubleSpinBoxes_K = [
        self.dlg.doubleSpinBox_FAD_B1_K,
        self.dlg.doubleSpinBox_FAD_B2_K,
        self.dlg.doubleSpinBox_FAD_B3_K,
        self.dlg.doubleSpinBox_FAD_B4_K,
        self.dlg.doubleSpinBox_FAD_B5_K,
        self.dlg.doubleSpinBox_FAD_B8A_K,
        self.dlg.doubleSpinBox_FAD_B9_K,
        self.dlg.doubleSpinBox_FAD_B10_K,
        self.dlg.doubleSpinBox_FAD_B11_K]
        
        DoubleSpinBoxes_x = [
        self.dlg.doubleSpinBox_FAD_B1_x,
        self.dlg.doubleSpinBox_FAD_B2_x,
        self.dlg.doubleSpinBox_FAD_B3_x,
        self.dlg.doubleSpinBox_FAD_B4_x,
        self.dlg.doubleSpinBox_FAD_B5_x,
        self.dlg.doubleSpinBox_FAD_B8A_x,
        self.dlg.doubleSpinBox_FAD_B9_x,
        self.dlg.doubleSpinBox_FAD_B10_x,
        self.dlg.doubleSpinBox_FAD_B11_x]

        # Reset value K
        for DSbox in DoubleSpinBoxes_K:
            DSbox.setValue(0)

        # Reset value x
        for DSbox in DoubleSpinBoxes_x:
            DSbox.setValue(0)

        # Reset checkbox
        for CKbox in CheckBoxes:
            CKbox.setCheckState(False)

        print("restored Features AD tab")  

###################################################################################################

    # OWA TAB #
    def reset_OWA_tab(self):

        # OWA reset check
        self.dlg.checkBox_OWA_AND.setCheckState(False)
        self.dlg.checkBox_OWA_almostAND.setCheckState(False)
        self.dlg.checkBox_OWA_AVERAGE.setCheckState(False)
        self.dlg.checkBox_OWA_almostOR.setCheckState(False)
        self.dlg.checkBox_OWA_OR.setCheckState(False)
        
        # OWA reset radiobutton for Seed
        self.dlg.radioButton_OWA_S_AND.setChecked(True)
        self.dlg.radioButton_OWA_S_almostAND.setChecked(False)
        self.dlg.radioButton_OWA_S_AVERAGE.setChecked(False)
        self.dlg.radioButton_OWA_S_almostOR.setChecked(False)
        self.dlg.radioButton_OWA_S_OR.setChecked(False)

        # OWA reset radiobutton for Grow
        self.dlg.radioButton_OWA_G_AND.setChecked(False)
        self.dlg.radioButton_OWA_G_almostAND.setChecked(False)
        self.dlg.radioButton_OWA_G_AVERAGE.setChecked(False)
        self.dlg.radioButton_OWA_G_almostOR.setChecked(False)
        self.dlg.radioButton_OWA_G_OR.setChecked(True)
        
        # OWA reset line edit
        self.dlg.lineEdit_OWA_AND.clear()
        self.dlg.lineEdit_OWA_almostAND.clear()
        self.dlg.lineEdit_OWA_AVERAGE.clear()
        self.dlg.lineEdit_OWA_almostOR.clear()
        self.dlg.lineEdit_OWA_OR.clear()

        # OWA reset check for display results
        self.dlg.checkBox_OWA_display.setCheckState(False)
       
        print("restored OWA tab")  

###################################################################################################

    # REGION GROWING TAB #
    def reset_RG_tab(self):

        # RG reset threshold value
        threshold_seed = 0.9
        threshold_grow = 0.1
        self.dlg.doubleSpinBox_RG_seed.setValue(threshold_seed)
        self.dlg.doubleSpinBox_RG_grow.setValue(threshold_grow)
        
        # RG reset check for display result
        self.dlg.checkBox_RG_display.setCheckState(False)
        
        # RG reset line edit
        self.dlg.lineEdit_RG_result.clear()
        print("restored RG tab")     
 
###################################################################################################
###################################################################################################
###################################################################################################
    

    def test(self):

        if self.dlg.spinBox_Error.value()==0:
            self.window = QtWidgets.QDialog()
            self.ui = Ui_Error()
            self.ui.setupUi(self.window)
            self.window.show()
            canary=0
            a=2+7
            return
            print(a)
        
        else:
            canary=1
            a=2+5
            print(a)
        
        print("canary = ",canary)
        
###################################################################################################     
###################################################################################################
###################################################################################################
# line of code in order to save output using tool button

    def select_output_file_AND(self):
        filename_AND, _filter = QFileDialog.getSaveFileName(self.dlg, "Select output file","",'*.tif')
        self.dlg.lineEdit_OWA_AND.setText(filename_AND)

   
    def select_output_file_almostAND(self):
        filename_almostAND, _filter = QFileDialog.getSaveFileName(self.dlg, "Select output file","",'*.tif')
        self.dlg.lineEdit_OWA_almostAND.setText(filename_almostAND)

   
    def select_output_file_AVERAGE(self):
        filename_AVERAGE, _filter = QFileDialog.getSaveFileName(self.dlg, "Select output file","",'*.tif')
        self.dlg.lineEdit_OWA_AVERAGE.setText(filename_AVERAGE)

   
    def select_output_file_almostOR(self):
        filename_almostOR, _filter = QFileDialog.getSaveFileName(self.dlg, "Select output file","",'*.tif')
        self.dlg.lineEdit_OWA_almostOR.setText(filename_almostOR)

   
    def select_output_file_OR(self):
        filename_OR, _filter = QFileDialog.getSaveFileName(self.dlg, "Select output file","",'*.tif')
        self.dlg.lineEdit_OWA_OR.setText(filename_OR)

###################

    def select_output_file_RG(self):
        filename_RG, _filter = QFileDialog.getSaveFileName(self.dlg, "Select output file","",'*.tif')
        self.dlg.lineEdit_RG_result.setText(filename_RG)



###################################################################################################     
###################################################################################################
###################################################################################################

#  This part of the script contains the code about the reading of the input layers,
#  the computation of the features (post and delta), the computation of the membership degree
#  appling the membership function, and finally the integration (using the OWA) of all these
#  information in order to obtain a single information  
# 
#  The process is executed when the button "COMPUTE OWA" is clicked             

    def ComputeOWA(self):
        
        Pre_name= str(self.dlg.comboBox_prefire.currentText())
        Pre_info = QgsProject.instance().mapLayersByName(Pre_name)
        Pre_path = Pre_info[0].dataProvider().dataSourceUri()

        Post_name = str(self.dlg.comboBox_postfire.currentText())       
        Post_info = QgsProject.instance().mapLayersByName(Post_name)
        Post_path = Post_info[0].dataProvider().dataSourceUri()
        #print(Pre_path)
        #print(Post_path)

        if self.dlg.checkBox_input_B1.isChecked():
            Band1=self.dlg.spinBox_input_B1.value()
        else:
            Band1=np.nan

        if self.dlg.checkBox_input_B2.isChecked():
            Band2=self.dlg.spinBox_input_B2.value()
        else:
            Band2=np.nan

        if self.dlg.checkBox_input_B3.isChecked():
            Band3=self.dlg.spinBox_input_B3.value()
        else:
            Band3=np.nan

        if self.dlg.checkBox_input_B4.isChecked():
            Band4=self.dlg.spinBox_input_B4.value()
        else:
            Band4=np.nan

        if self.dlg.checkBox_input_B5.isChecked():
            Band5=self.dlg.spinBox_input_B5.value()
        else:
            Band5=np.nan

        if self.dlg.checkBox_input_B6.isChecked():
            Band6=self.dlg.spinBox_input_B6.value()
        else:
            Band6=np.nan

        if self.dlg.checkBox_input_B7.isChecked():
            Band7=self.dlg.spinBox_input_B7.value()
        else:
            Band7=np.nan

        if self.dlg.checkBox_input_B8.isChecked():
            Band8=self.dlg.spinBox_input_B8.value()
        else:
            Band8=np.nan

        if self.dlg.checkBox_input_B8A.isChecked():
            Band8A=self.dlg.spinBox_input_B8A.value()
        else:
            Band8A=np.nan

        if self.dlg.checkBox_input_B9.isChecked():
            Band9=self.dlg.spinBox_input_B9.value()
        else:
            Band9=np.nan 

        if self.dlg.checkBox_input_B10.isChecked():
            Band10=self.dlg.spinBox_input_B10.value()
        else:
            Band10=np.nan

        if self.dlg.checkBox_input_B11.isChecked():
            Band11=self.dlg.spinBox_input_B11.value()
        else:
            Band11=np.nan

        if self.dlg.checkBox_input_B12.isChecked():
            Band12=self.dlg.spinBox_input_B12.value()
        else:
            Band12=np.nan

        BandsList=[Band1,Band2,Band3,Band4,Band5,Band6,Band7,Band8,Band8A,Band9,Band10,Band11,Band12]
        
        Data=ReadingData(Pre_path,Post_path)    
        #print("numero bande:",Magic.Bands)
        #for i in range(Magic.Bands):
            #print("Banda:",i,")",Magic.Post_matrix[i,0,0])
            #print("Banda:",i,")",Magic.Pre_matrix[i,0,0])
            #print("Banda:",i,")",Magic.Delta_matrix[i,0,0])
        
        
        ###################################################################################################
        # Apply the Membership Function (K and x0 come from the user as input) on the selected layer 
        ###################################################################################################
        
        FinalBandList=[]
    
        # FEATURES DEFAULT
        if self.dlg.checkBox_FD_postB6.isChecked():
            K=self.dlg.doubleSpinBox_FD_postB6_K.value()
            x=self.dlg.doubleSpinBox_FD_postB6_x.value()
            # -1 is necessary in order to allign the order of the bands
            # user starts to count from 1 (B1,B2...), instead pyhton starts to count from 0
            
            # SE BAND=NAN INSERIRE PAGINA DI ERORRE: BANDA NON SELEZIONATA 
            # O FETURES SELEZIONATA COME ERRORE
            layer=Data.Second_matrix[Band6-1]
            MD_postB6 = MembershipFunction(layer,K,x).MD
            FinalBandList.append(MD_postB6)

        if self.dlg.checkBox_FD_postB7.isChecked():
            K=self.dlg.doubleSpinBox_FD_postB7_K.value()
            x=self.dlg.doubleSpinBox_FD_postB7_x.value()
            # -1 is necessary in order to allign the order of the bands
            # user starts to count from 1 (B1,B2...), instead pyhton starts to count from 0
            
            # SE BAND=NAN INSERIRE PAGINA DI ERORRE: BANDA NON SELEZIONATA 
            # O FETURES SELEZIONATA COME ERRORE
            layer=Data.Second_matrix[Band7-1]
            MD_postB7 = MembershipFunction(layer,K,x).MD
            FinalBandList.append(MD_postB7)

        if self.dlg.checkBox_FD_postNIR.isChecked():
            K=self.dlg.doubleSpinBox_FD_postNIR_K.value()
            x=self.dlg.doubleSpinBox_FD_postNIR_x.value()
            # -1 is necessary in order to allign the order of the bands
            # user starts to count from 1 (B1,B2...), instead pyhton starts to count from 0
            
            # SE BAND=NAN INSERIRE PAGINA DI ERORRE: BANDA NON SELEZIONATA 
            # O FETURES SELEZIONATA COME ERRORE
            layer=Data.Second_matrix[Band8-1]
            MD_postB8 = MembershipFunction(layer,K,x).MD
            FinalBandList.append(MD_postB8)

        if self.dlg.checkBox_FD_deltaB6.isChecked():
            K=self.dlg.doubleSpinBox_FD_deltaB6_K.value()
            x=self.dlg.doubleSpinBox_FD_deltaB6_x.value()
            # -1 is necessary in order to allign the order of the bands
            # user starts to count from 1 (B1,B2...), instead pyhton starts to count from 0
            
            # SE BAND=NAN INSERIRE PAGINA DI ERORRE: BANDA NON SELEZIONATA 
            # O FETURES SELEZIONATA COME ERRORE
            layer=Data.Delta_matrix[Band6-1]
            MD_deltaB6 = MembershipFunction(layer,K,x).MD
            FinalBandList.append(MD_deltaB6)

        if self.dlg.checkBox_FD_deltaB7.isChecked():
            K=self.dlg.doubleSpinBox_FD_deltaB7_K.value()
            x=self.dlg.doubleSpinBox_FD_deltaB7_x.value()
            # -1 is necessary in order to allign the order of the bands
            # user starts to count from 1 (B1,B2...), instead pyhton starts to count from 0
            
            # SE BAND=NAN INSERIRE PAGINA DI ERORRE: BANDA NON SELEZIONATA 
            # O FETURES SELEZIONATA COME ERRORE
            layer=Data.Delta_matrix[Band7-1]
            MD_deltaB7 = MembershipFunction(layer,K,x).MD
            FinalBandList.append(MD_deltaB7)

        if self.dlg.checkBox_FD_deltaNIR.isChecked():
            K=self.dlg.doubleSpinBox_FD_deltaNIR_K.value()
            x=self.dlg.doubleSpinBox_FD_deltaNIR_x.value()
            # -1 is necessary in order to allign the order of the bands
            # user starts to count from 1 (B1,B2...), instead pyhton starts to count from 0
            
            # SE BAND=NAN INSERIRE PAGINA DI ERORRE: BANDA NON SELEZIONATA 
            # O FETURES SELEZIONATA COME ERRORE
            layer=Data.Delta_matrix[Band8-1]
            MD_deltaB8 = MembershipFunction(layer,K,x).MD
            FinalBandList.append(MD_deltaB8)

        if self.dlg.checkBox_FD_deltaB12.isChecked():
            K=self.dlg.doubleSpinBox_FD_deltaB12_K.value()
            x=self.dlg.doubleSpinBox_FD_deltaB12_x.value()
            # -1 is necessary in order to allign the order of the bands
            # user starts to count from 1 (B1,B2...), instead pyhton starts to count from 0
            
            # SE BAND=NAN INSERIRE PAGINA DI ERORRE: BANDA NON SELEZIONATA 
            # O FETURES SELEZIONATA COME ERRORE
            
            layer=Data.Delta_matrix[Band12-1]
                        
            MD_deltaB12 = MembershipFunction(layer,K,x).MD
            FinalBandList.append(MD_deltaB12)

        # FEATURES ADVANCED POST
        if self.dlg.checkBox_FAP_B1.isChecked():
            K=self.dlg.doubleSpinBox_FAP_B1_K.value()
            x=self.dlg.doubleSpinBox_FAP_B1_x.value()
            # -1 is necessary in order to allign the order of the bands
            # user starts to count from 1 (B1,B2...), instead pyhton starts to count from 0
            
            # SE BAND=NAN INSERIRE PAGINA DI ERORRE: BANDA NON SELEZIONATA 
            # O FETURES SELEZIONATA COME ERRORE
            layer=Data.Second_matrix[Band1-1]
            MD_postB1 = MembershipFunction(layer,K,x).MD
            FinalBandList.append(MD_postB1)

        if self.dlg.checkBox_FAP_B2.isChecked():
            K=self.dlg.doubleSpinBox_FAP_B2_K.value()
            x=self.dlg.doubleSpinBox_FAP_B2_x.value()
            # -1 is necessary in order to allign the order of the bands
            # user starts to count from 1 (B1,B2...), instead pyhton starts to count from 0
            
            # SE BAND=NAN INSERIRE PAGINA DI ERORRE: BANDA NON SELEZIONATA 
            # O FETURES SELEZIONATA COME ERRORE
            layer=Data.Second_matrix[Band2-1]
            MD_postB2 = MembershipFunction(layer,K,x).MD
            FinalBandList.append(MD_postB2)

        if self.dlg.checkBox_FAP_B3.isChecked():
            K=self.dlg.doubleSpinBox_FAP_B3_K.value()
            x=self.dlg.doubleSpinBox_FAP_B3_x.value()
            # -1 is necessary in order to allign the order of the bands
            # user starts to count from 1 (B1,B2...), instead pyhton starts to count from 0
            
            # SE BAND=NAN INSERIRE PAGINA DI ERORRE: BANDA NON SELEZIONATA 
            # O FETURES SELEZIONATA COME ERRORE
            layer=Data.Second_matrix[Band3-1]
            MD_postB3 = MembershipFunction(layer,K,x).MD
            FinalBandList.append(MD_postB3)

        if self.dlg.checkBox_FAP_B4.isChecked():
            K=self.dlg.doubleSpinBox_FAP_B4_K.value()
            x=self.dlg.doubleSpinBox_FAP_B4_x.value()
            # -1 is necessary in order to allign the order of the bands
            # user starts to count from 1 (B1,B2...), instead pyhton starts to count from 0
            
            # SE BAND=NAN INSERIRE PAGINA DI ERORRE: BANDA NON SELEZIONATA 
            # O FETURES SELEZIONATA COME ERRORE
            layer=Data.Second_matrix[Band4-1]
            MD_postB4 = MembershipFunction(layer,K,x).MD
            FinalBandList.append(MD_postB4)

        if self.dlg.checkBox_FAP_B5.isChecked():
            K=self.dlg.doubleSpinBox_FAP_B5_K.value()
            x=self.dlg.doubleSpinBox_FAP_B5_x.value()
            # -1 is necessary in order to allign the order of the bands
            # user starts to count from 1 (B1,B2...), instead pyhton starts to count from 0
            
            # SE BAND=NAN INSERIRE PAGINA DI ERORRE: BANDA NON SELEZIONATA 
            # O FETURES SELEZIONATA COME ERRORE
            layer=Data.Second_matrix[Band5-1]
            MD_postB5 = MembershipFunction(layer,K,x).MD
            FinalBandList.append(MD_postB5)

        if self.dlg.checkBox_FAP_B8A.isChecked():
            K=self.dlg.doubleSpinBox_FAP_B8A_K.value()
            x=self.dlg.doubleSpinBox_FAP_B8A_x.value()
            # -1 is necessary in order to allign the order of the bands
            # user starts to count from 1 (B1,B2...), instead pyhton starts to count from 0
            
            # SE BAND=NAN INSERIRE PAGINA DI ERORRE: BANDA NON SELEZIONATA 
            # O FETURES SELEZIONATA COME ERRORE
            layer=Data.Second_matrix[Band8A-1]
            MD_postB8A = MembershipFunction(layer,K,x).MD
            FinalBandList.append(MD_postB8A)

        if self.dlg.checkBox_FAP_B9.isChecked():
            K=self.dlg.doubleSpinBox_FAP_B9_K.value()
            x=self.dlg.doubleSpinBox_FAP_B9_x.value()
            # -1 is necessary in order to allign the order of the bands
            # user starts to count from 1 (B1,B2...), instead pyhton starts to count from 0
            
            # SE BAND=NAN INSERIRE PAGINA DI ERORRE: BANDA NON SELEZIONATA 
            # O FETURES SELEZIONATA COME ERRORE
            layer=Data.Second_matrix[Band9-1]
            MD_postB9 = MembershipFunction(layer,K,x).MD
            FinalBandList.append(MD_postB9)

        if self.dlg.checkBox_FAP_B10.isChecked():
            K=self.dlg.doubleSpinBox_FAP_B10_K.value()
            x=self.dlg.doubleSpinBox_FAP_B10_x.value()
            # -1 is necessary in order to allign the order of the bands
            # user starts to count from 1 (B1,B2...), instead pyhton starts to count from 0
            
            # SE BAND=NAN INSERIRE PAGINA DI ERORRE: BANDA NON SELEZIONATA 
            # O FETURES SELEZIONATA COME ERRORE
            layer=Data.Second_matrix[Band10-1]
            MD_postB10 = MembershipFunction(layer,K,x).MD
            FinalBandList.append(MD_postB10)

        if self.dlg.checkBox_FAP_B11.isChecked():
            K=self.dlg.doubleSpinBox_FAP_B11_K.value()
            x=self.dlg.doubleSpinBox_FAP_B11_x.value()
            # -1 is necessary in order to allign the order of the bands
            # user starts to count from 1 (B1,B2...), instead pyhton starts to count from 0
            
            # SE BAND=NAN INSERIRE PAGINA DI ERORRE: BANDA NON SELEZIONATA 
            # O FETURES SELEZIONATA COME ERRORE
            layer=Data.Second_matrix[Band11-1]
            MD_postB11 = MembershipFunction(layer,K,x).MD
            FinalBandList.append(MD_postB11)

        if self.dlg.checkBox_FAP_B12.isChecked():
            K=self.dlg.doubleSpinBox_FAP_B12_K.value()
            x=self.dlg.doubleSpinBox_FAP_B12_x.value()
            # -1 is necessary in order to allign the order of the bands
            # user starts to count from 1 (B1,B2...), instead pyhton starts to count from 0
            
            # SE BAND=NAN INSERIRE PAGINA DI ERORRE: BANDA NON SELEZIONATA 
            # O FETURES SELEZIONATA COME ERRORE
            layer=Data.Second_matrix[Band12-1]
            MD_postB12 = MembershipFunction(layer,K,x).MD
            FinalBandList.append(MD_postB12)

        # FEATURES ADVANCED DELTA
        if self.dlg.checkBox_FAD_B1.isChecked():
            K=self.dlg.doubleSpinBox_FAD_B1_K.value()
            x=self.dlg.doubleSpinBox_FAD_B1_x.value()
            # -1 is necessary in order to allign the order of the bands
            # user starts to count from 1 (B1,B2...), instead pyhton starts to count from 0
            
            # SE BAND=NAN INSERIRE PAGINA DI ERORRE: BANDA NON SELEZIONATA 
            # O FETURES SELEZIONATA COME ERRORE
            layer=Data.Delta_matrix[Band1-1]
            MD_deltaB1 = MembershipFunction(layer,K,x).MD
            FinalBandList.append(MD_deltaB1)

        if self.dlg.checkBox_FAD_B2.isChecked():
            K=self.dlg.doubleSpinBox_FAD_B2_K.value()
            x=self.dlg.doubleSpinBox_FAD_B2_x.value()
            # -1 is necessary in order to allign the order of the bands
            # user starts to count from 1 (B1,B2...), instead pyhton starts to count from 0
            
            # SE BAND=NAN INSERIRE PAGINA DI ERORRE: BANDA NON SELEZIONATA 
            # O FETURES SELEZIONATA COME ERRORE
            layer=Data.Delta_matrix[Band2-1]
            MD_deltaB2 = MembershipFunction(layer,K,x).MD
            FinalBandList.append(MD_deltaB2)

        if self.dlg.checkBox_FAD_B3.isChecked():
            K=self.dlg.doubleSpinBox_FAD_B3_K.value()
            x=self.dlg.doubleSpinBox_FAD_B3_x.value()
            # -1 is necessary in order to allign the order of the bands
            # user starts to count from 1 (B1,B2...), instead pyhton starts to count from 0
            
            # SE BAND=NAN INSERIRE PAGINA DI ERORRE: BANDA NON SELEZIONATA 
            # O FETURES SELEZIONATA COME ERRORE
            layer=Data.Delta_matrix[Band3-1]
            MD_deltaB3 = MembershipFunction(layer,K,x).MD
            FinalBandList.append(MD_deltaB3)

        if self.dlg.checkBox_FAD_B4.isChecked():
            K=self.dlg.doubleSpinBox_FAD_B4_K.value()
            x=self.dlg.doubleSpinBox_FAD_B4_x.value()
            # -1 is necessary in order to allign the order of the bands
            # user starts to count from 1 (B1,B2...), instead pyhton starts to count from 0
            
            # SE BAND=NAN INSERIRE PAGINA DI ERORRE: BANDA NON SELEZIONATA 
            # O FETURES SELEZIONATA COME ERRORE
            layer=Data.Delta_matrix[Band4-1]
            MD_deltaB4 = MembershipFunction(layer,K,x).MD
            FinalBandList.append(MD_deltaB4)

        if self.dlg.checkBox_FAD_B5.isChecked():
            K=self.dlg.doubleSpinBox_FAD_B5_K.value()
            x=self.dlg.doubleSpinBox_FAD_B5_x.value()
            # -1 is necessary in order to allign the order of the bands
            # user starts to count from 1 (B1,B2...), instead pyhton starts to count from 0
            
            # SE BAND=NAN INSERIRE PAGINA DI ERORRE: BANDA NON SELEZIONATA 
            # O FETURES SELEZIONATA COME ERRORE
            layer=Data.Delta_matrix[Band5-1]
            MD_deltaB5 = MembershipFunction(layer,K,x).MD
            FinalBandList.append(MD_deltaB5)

        if self.dlg.checkBox_FAD_B8A.isChecked():
            K=self.dlg.doubleSpinBox_FAD_B8A_K.value()
            x=self.dlg.doubleSpinBox_FAD_B8A_x.value()
            # -1 is necessary in order to allign the order of the bands
            # user starts to count from 1 (B1,B2...), instead pyhton starts to count from 0
            
            # SE BAND=NAN INSERIRE PAGINA DI ERORRE: BANDA NON SELEZIONATA 
            # O FETURES SELEZIONATA COME ERRORE
            layer=Data.Delta_matrix[Band8A-1]
            MD_deltaB8A = MembershipFunction(layer,K,x).MD
            FinalBandList.append(MD_deltaB8A)

        if self.dlg.checkBox_FAD_B9.isChecked():
            K=self.dlg.doubleSpinBox_FAD_B9_K.value()
            x=self.dlg.doubleSpinBox_FAD_B9_x.value()
            # -1 is necessary in order to allign the order of the bands
            # user starts to count from 1 (B1,B2...), instead pyhton starts to count from 0
            
            # SE BAND=NAN INSERIRE PAGINA DI ERORRE: BANDA NON SELEZIONATA 
            # O FETURES SELEZIONATA COME ERRORE
            layer=Data.Delta_matrix[Band9-1]
            MD_deltaB9 = MembershipFunction(layer,K,x).MD
            FinalBandList.append(MD_deltaB9)

        if self.dlg.checkBox_FAD_B10.isChecked():
            K=self.dlg.doubleSpinBox_FAD_B10_K.value()
            x=self.dlg.doubleSpinBox_FAD_B10_x.value()
            # -1 is necessary in order to allign the order of the bands
            # user starts to count from 1 (B1,B2...), instead pyhton starts to count from 0
            
            # SE BAND=NAN INSERIRE PAGINA DI ERORRE: BANDA NON SELEZIONATA 
            # O FETURES SELEZIONATA COME ERRORE
            layer=Data.Delta_matrix[Band10-1]
            MD_deltaB10 = MembershipFunction(layer,K,x).MD
            FinalBandList.append(MD_deltaB10)

        if self.dlg.checkBox_FAD_B11.isChecked():
            K=self.dlg.doubleSpinBox_FAD_B11_K.value()
            x=self.dlg.doubleSpinBox_FAD_B11_x.value()
            # -1 is necessary in order to allign the order of the bands
            # user starts to count from 1 (B1,B2...), instead pyhton starts to count from 0
            
            # SE BAND=NAN INSERIRE PAGINA DI ERORRE: BANDA NON SELEZIONATA 
            # O FETURES SELEZIONATA COME ERRORE
            layer=Data.Delta_matrix[Band11-1]
            MD_deltaB11 = MembershipFunction(layer,K,x).MD
            FinalBandList.append(MD_deltaB11)


        # ora ho la matrice finale con tutti i membership degree devo andare a calcolare gli owa 
        # per farlo devo guardare pixel per pixel tutti i valori che ho [i,j,k]
        # tengo fisso j,k (il pixel) e faccio scorrere i
        # per l'AND dopo il sort() è l'ultimo elemento della lista, lista[-1]
        # per l'OR dopo il sort() è il primo elemento della lista, lista[0]
        # per la media serve il numero di elementi ( che corrisponde a i+1 poiche parte da zero)
        # almost AND dopo il sort() è il penultimo elemento della lista, lista[-2]
        # almost OR dopo il sort() è il secondo elemento della lista, lista[1]

        # questo passaggio mi consente di trasformare la lista in un array meglio dire un tensore
        FinalBandMatix=np.array(FinalBandList)
    
        # con questa matrice devo scriverla in un file .tif che è un layer e sarà input del region growing
        if self.dlg.checkBox_OWA_AND.isChecked() or self.dlg.radioButton_OWA_S_AND.isChecked() or \
            self.dlg.radioButton_OWA_G_AND.isChecked():

            OWA_index=1
            OWA=OrderedWeigthAverage(OWA_index,FinalBandMatix)
            print("AND",np.shape(OWA.Integrated_matrix),OWA.Integrated_matrix[0,0])
            #devo scrivere il layer:
            # path è o salvo il file nella medesima cartella dell'input cambiandone il nome
            # oppure il path è la line di testo inserita dell'utente
            
            outputfile = self.dlg.lineEdit_OWA_AND.text()
            
            # if the outputfile path is not specified the plugin uses the same path of one of the two input
            # files, in particular the seed layer path
            if not outputfile:
                path_index=0
                path=Pre_path
            # otherwise it uses the path specified by the user
            else:
                path_index=1
                path=outputfile
                
            self.OWA_AND = WriteLayer(path_index,path,OWA.Integrated_matrix,OWA.filename,Data.gt,Data.proj)
            #se è checcato il display allora mostra
            if self.dlg.checkBox_OWA_display.isChecked():
                #al posto dei punti di domanda devo mettere il path ddel file da visualizzare
                iface.addRasterLayer(self.OWA_AND.output_path, "OWA_AND")

        if self.dlg.checkBox_OWA_almostAND.isChecked() or self.dlg.radioButton_OWA_S_almostAND.isChecked() or \
            self.dlg.radioButton_OWA_G_almostAND.isChecked():

            OWA_index=2
            OWA=OrderedWeigthAverage(OWA_index,FinalBandMatix)
            print("almost_AND",np.shape(OWA.Integrated_matrix),OWA.Integrated_matrix[0,0])
            outputfile = self.dlg.lineEdit_OWA_almostAND.text()

            if not outputfile:
                path_index=0
                path=Pre_path
            else:
                path_index=1
                path=outputfile
                
            self.OWA_almostAND = WriteLayer(path_index,path,OWA.Integrated_matrix,OWA.filename,Data.gt,Data.proj)
    
            if self.dlg.checkBox_OWA_display.isChecked():
                iface.addRasterLayer(self.OWA_almostAND.output_path, "OWA_almostAND")
        
        if self.dlg.checkBox_OWA_AVERAGE.isChecked() or self.dlg.radioButton_OWA_S_AVERAGE.isChecked() or \
            self.dlg.radioButton_OWA_G_AVERAGE.isChecked():
            OWA_index=3
            OWA=OrderedWeigthAverage(OWA_index,FinalBandMatix)
            print("AVERAGE",np.shape(OWA.Integrated_matrix),OWA.Integrated_matrix[0,0])
            outputfile = self.dlg.lineEdit_OWA_AVERAGE.text()

            if not outputfile:
                path_index=0
                path=Pre_path
            else:
                path_index=1
                path=outputfile
                
            self.OWA_AVERAGE = WriteLayer(path_index,path,OWA.Integrated_matrix,OWA.filename,Data.gt,Data.proj)
    
            if self.dlg.checkBox_OWA_display.isChecked():
                iface.addRasterLayer(self.OWA_AVERAGE.output_path, "OWA_AVERAGE")
                   
        if self.dlg.checkBox_OWA_almostOR.isChecked() or self.dlg.radioButton_OWA_S_almostOR.isChecked() or \
            self.dlg.radioButton_OWA_G_almostOR.isChecked():
            OWA_index=4
            OWA=OrderedWeigthAverage(OWA_index,FinalBandMatix)
            print("almost_OR",np.shape(OWA.Integrated_matrix),OWA.Integrated_matrix[0,0])
            outputfile = self.dlg.lineEdit_OWA_almostOR.text()

            if not outputfile:
                path_index=0
                path=Pre_path
            else:
                path_index=1
                path=outputfile
                
            self.OWA_almostOR = WriteLayer(path_index,path,OWA.Integrated_matrix,OWA.filename,Data.gt,Data.proj)
    
            if self.dlg.checkBox_OWA_display.isChecked():
                iface.addRasterLayer(self.OWA_almostOR.output_path, "OWA_almostOR")
        
        if self.dlg.checkBox_OWA_OR.isChecked() or self.dlg.radioButton_OWA_S_OR.isChecked() or \
            self.dlg.radioButton_OWA_G_OR.isChecked():
            OWA_index=5
            OWA=OrderedWeigthAverage(OWA_index,FinalBandMatix)
            print("OR",np.shape(OWA.Integrated_matrix),OWA.Integrated_matrix[0,0])
            outputfile = self.dlg.lineEdit_OWA_OR.text()

            if not outputfile:
                path_index=0
                path=Pre_path
            else:
                path_index=1
                path=outputfile
                
            self.OWA_OR = WriteLayer(path_index,path,OWA.Integrated_matrix,OWA.filename,Data.gt,Data.proj)
    
            if self.dlg.checkBox_OWA_display.isChecked():
                iface.addRasterLayer(self.OWA_OR.output_path, "OWA_OR")
           

###################################################################################################
###################################################################################################
###################################################################################################
#  This part of the script contains the code about the appliocation of the Region Growing Algorithm 
#  The process is executed when the button "COMPUTE RG" is clicked   
    
    def ComputeRG(self):
        print("bottone premuto RG")


       
        Seed_value = round(self.dlg.doubleSpinBox_RG_seed.value(),2)
        Grow_value = round(self.dlg.doubleSpinBox_RG_grow.value(),2)


        # QUESTO VA FATTO SE L'UTENTE NON SELEZIONA NESSUN INPUT ALTRIMENTI DEVO SELEZIONARE COME IMPUT
        # PER IL RG CIO' CHE L'UTENTE PASSA
        if self.dlg.groupBox_RG_input.isChecked():
        
            Seed_name = str(self.dlg.comboBox_RG_seed.currentText())
            Seed_info = QgsProject.instance().mapLayersByName(Seed_name)
            Seed_path = Seed_info[0].dataProvider().dataSourceUri()

            Grow_name = str(self.dlg.comboBox_RG_grow.currentText())       
            Grow_info = QgsProject.instance().mapLayersByName(Grow_name)
            Grow_path = Grow_info[0].dataProvider().dataSourceUri()
            
            Seed_file = Seed_path 
            Grow_file = Grow_path
        
        else:
            # il layer che utilizzo per il seed e per il grow è deciso dai radio buttons nella pagina dell'owa
            if self.dlg.radioButton_OWA_S_AND.isChecked():
                Seed_file = self.OWA_AND.output_path

            if self.dlg.radioButton_OWA_S_almostAND.isChecked():
                Seed_file = self.OWA_almostAND.output_path

            if self.dlg.radioButton_OWA_S_AVERAGE.isChecked():
                Seed_file = self.OWA_AVERAGE.output_path

            if self.dlg.radioButton_OWA_S_almostOR.isChecked():
                Seed_file = self.OWA_almostOR.output_path

            if self.dlg.radioButton_OWA_S_OR.isChecked():
                Seed_file = self.OWA_OR.output_path

            if self.dlg.radioButton_OWA_G_AND.isChecked():
                Grow_file = self.OWA_AND.output_path

            if self.dlg.radioButton_OWA_G_almostAND.isChecked():
                Grow_file = self.OWA_almostAND.output_path

            if self.dlg.radioButton_OWA_G_AVERAGE.isChecked():
                Grow_file = self.OWA_AVERAGE.output_path

            if self.dlg.radioButton_OWA_G_almostOR.isChecked():
                Grow_file = self.OWA_almostOR.output_path

            if self.dlg.radioButton_OWA_G_OR.isChecked():
                Grow_file = self.OWA_OR.output_path 

        
        DataRG = ReadingData(Seed_file,Grow_file) 
        Seed_matrix = DataRG.First_matrix
        Grow_matrix = DataRG.Second_matrix

        #fare il binary delle matrici e poi fare il RG

        RG=RegionGrowing(Seed_value,Grow_value,Seed_matrix,Grow_matrix)

        RG_outputfile = self.dlg.lineEdit_RG_result.text()
        
        if not RG_outputfile:
                path_index = 0
                path = Seed_file
                filename = "RegionGrowing_result.tif"     
        else:
                path_index = 1
                path = RG_outputfile
                filename="null"
        
        self.RG_result = WriteLayer(path_index,path,RG.Result_matrix,filename,DataRG.gt,DataRG.proj)
        
        if self.dlg.checkBox_RG_display.isChecked():
                iface.addRasterLayer(self.RG_result.output_path, "RG_result")

###################################################################################################
###################################################################################################
###################################################################################################


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = BADDialog()
            
            self.dlg.pushButton_input_reset.clicked.connect(self.reset_input_tab)
            self.dlg.pushButton_Features_D_reset.clicked.connect(self.reset_Features_D_tab)
            self.dlg.pushButton_Features_AP_reset.clicked.connect(self.reset_Features_AP_tab)
            self.dlg.pushButton_Features_AD_reset.clicked.connect(self.reset_Features_AD_tab)
            self.dlg.pushButton_OWA_reset.clicked.connect(self.reset_OWA_tab)
            self.dlg.pushButton_RG_reset.clicked.connect(self.reset_RG_tab)
            self.dlg.pushButton_Error.clicked.connect(self.test)

            self.dlg.toolButton_OWA_AND.clicked.connect(self.select_output_file_AND)
            self.dlg.toolButton_OWA_almostAND.clicked.connect(self.select_output_file_almostAND)
            self.dlg.toolButton_OWA_AVERAGE.clicked.connect(self.select_output_file_AVERAGE)
            self.dlg.toolButton_OWA_almostOR.clicked.connect(self.select_output_file_almostOR)
            self.dlg.toolButton_OWA_OR.clicked.connect(self.select_output_file_OR)

            self.dlg.pushButton_OWA_run.clicked.connect(self.ComputeOWA)

            self.dlg.toolButton_RG_result.clicked.connect(self.select_output_file_RG)
            self.dlg.pushButton_RG_run.clicked.connect(self.ComputeRG)
            
        
        #Fetch the currently loaded layers
        layers = QgsProject.instance().layerTreeRoot().children()
        
        #Clear the contents of the comboBox from previous runs
        self.dlg.comboBox_prefire.clear()
        self.dlg.comboBox_postfire.clear()

        self.dlg.comboBox_RG_seed.clear()
        self.dlg.comboBox_RG_grow.clear()

        
        #populate the comboBox with names of all the loaded layers
        self.dlg.comboBox_prefire.addItems(['Select a Layer'])
        self.dlg.comboBox_postfire.addItems(['Select a Layer'])

        self.dlg.comboBox_prefire.addItems([layer.name() for layer in layers])
        self.dlg.comboBox_postfire.addItems([layer.name() for layer in layers])
      
        self.dlg.comboBox_RG_seed.addItems(['Select a Layer'])
        self.dlg.comboBox_RG_grow.addItems(['Select a Layer'])
        self.dlg.comboBox_RG_seed.addItems([layer.name() for layer in layers])
        self.dlg.comboBox_RG_grow.addItems([layer.name() for layer in layers])
        





        

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            self.ComputeOWA()
            self.ComputeRG()
            print("Fatto")