# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BAD
                                 A QGIS plugin
 BAD_Burned Area Detector
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-01-24
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Thomas Martinoli
        email                : th.martinoli96@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""


from osgeo import gdal
import numpy as np
# Initialize Qt resources from file resources.py
from .resources import *
#it is necessary to insert this line in order to make possible the import of data
from qgis.core import QgsProject
# Import the code for the dialog
from .BAD_dialog import BADDialog
import os.path

class ReadingData:
    def __init__(self,First_path,Second_path):
        print(First_path)
        print(Second_path)

        First_raster = gdal.Open(First_path, gdal.GA_ReadOnly) 
        Second_raster = gdal.Open(Second_path, gdal.GA_ReadOnly) 
        # Note GetRasterBand() takes band no. starting from 1 not 0

        self.First_matrix=First_raster.ReadAsArray()
        self.Second_matrix=Second_raster.ReadAsArray()

        F=self.First_matrix.astype(float)
        S=self.Second_matrix.astype(float)
        self.Delta_matrix=S-F
      
        self.Bands=First_raster.RasterCount
        self.gt = First_raster.GetGeoTransform()
        self.proj= First_raster.GetProjection()

class MembershipFunction:
    def __init__(self,Matrix,K,x):
        
        self.MD=1/(1+np.exp(-K*(Matrix/10000-x)))
        
class OrderedWeigthAverage:
    def __init__(self,index,FinalBandMatix):
        
        Row=FinalBandMatix.shape[1]
        Column=FinalBandMatix.shape[2]
        self.Integrated_matrix=np.empty([Row,Column])

        #AND
        if index==1:
            self.filename="OWA_AND.tif"
            for i in range (Row):
                for j in range (Column):
                    vector=FinalBandMatix[:,i,j]
                    if i==0 and j==0:
                        print(vector)
                    value=min(vector)
                    self.Integrated_matrix[i,j]=value

        #almost AND
        if index==2:
            self.filename="OWA_almostAND.tif"
            for i in range (Row):
                for j in range (Column):
                    vector=FinalBandMatix[:,i,j]
                    value=(np.sort(vector)[-1]+np.sort(vector)[-2])/2
                    self.Integrated_matrix[i,j]=value
        #AVERAGE
        if index==3:
            self.filename="OWA_AVERAGE.tif"
            for i in range (Row):
                for j in range (Column):
                    vector=FinalBandMatix[:,i,j]
                    value=np.mean(vector)
                    self.Integrated_matrix[i,j]=value
        #almost OR:
        if index==4:
            self.filename="OWA_almostOR.tif"
            for i in range (Row):
                for j in range (Column):
                    vector=FinalBandMatix[:,i,j]
                    value=(np.sort(vector)[0]+np.sort(vector)[1])/2
                    self.Integrated_matrix[i,j]=value
        #OR
        if index==5:      
            self.filename="OWA_OR.tif" 
            for i in range (Row):
                for j in range (Column):
                    vector=FinalBandMatix[:,i,j]
                    if i==0 and j==0:
                        print(vector)
                    value=max(vector)
                    self.Integrated_matrix[i,j]=value

class WriteLayer:
    def __init__(self,index,path,Integrated_matrix,filename,gt,proj):
        
        if index==0:
            # se indice zero significa che l'utente non ha specificato nulla per 
            # cui devo trasformare il path per salvare il file in formato .tif
            array_path=path.split('/')
            array_path[-1]=filename
            splitter="/"
            self.output_path=splitter.join(array_path)
        else:
            self.output_path=path
       
        driver = gdal.GetDriverByName("GTiff")
        driver.Register()
        outds = driver.Create(self.output_path, xsize=Integrated_matrix.shape[1],ysize=Integrated_matrix.shape[0],bands=1, eType= gdal.GDT_Float32)
        outds.SetGeoTransform(gt)
        outds.SetProjection(proj)
        outband = outds.GetRasterBand(1)
        outband.WriteArray(Integrated_matrix)
        outband.FlushCache()
        outband= None
        outds = None


class RegionGrowing:
    def __init__(self,Seed_threshold,Grow_threshold,Seed_matrix,Grow_matrix):

        Seed_binary = np.where(Seed_matrix<Seed_threshold,0,1)
        Grow_binary = np.where(Grow_matrix<Grow_threshold,0,1)
        self.Raster=np.array([Seed_binary,Grow_binary])

        RasterPP=self.Raster.copy()

        sizeRow=RasterPP[0].shape[0]
        sizeColumn=RasterPP[0].shape[1]
        
        M=0
        N=np.count_nonzero(RasterPP[0])
        
        print('prima del while')

        while N!=M:
            M=N
            for j in range(sizeRow):
                for k in range(sizeColumn):
                                    
                    #insertion of the neighbors that are not considered yet
                    
                    if RasterPP[0,j,k]==1:
                                            
                        # neighbor examination                
                        
                        # above-left   
                        if j>0 and k>0 and RasterPP[0,j-1,k-1]==0 and RasterPP[1,j-1,k-1]==1:
                            RasterPP[0,j-1,k-1]=1
                            
                        
                        # above
                        if j>0 and RasterPP[0,j-1,k]==0 and RasterPP[1,j-1,k]==1:
                            RasterPP[0,j-1,k]=1
                            
                        
                        #above-right
                        if j>0 and k<=sizeColumn-2 and RasterPP[0,j-1,k+1]==0 and RasterPP[1,j-1,k+1]==1:
                            RasterPP[0,j-1,k+1]=1
                            
                            
                        #left
                        if k>0 and RasterPP[0,j,k-1]==0 and RasterPP[1,j,k-1]==1:
                            RasterPP[0,j,k-1]=1
                            
                        #right
                        if k<=sizeColumn-2 and RasterPP[0,j,k+1]==0 and RasterPP[1,j,k+1]==1:
                            RasterPP[0,j,k+1]=1
                            
                        
                        #below-left    
                        if j<=sizeRow-2 and k>0 and RasterPP[0,j+1,k-1]==0 and RasterPP[1,j+1,k-1]==1:
                            RasterPP[0,j+1,k-1]=1
                            
                        
                        #below    
                        if j<=sizeRow-2 and RasterPP[0,j+1,k]==0 and RasterPP[1,j+1,k]==1:
                            RasterPP[0,j+1,k]=1
                            
                        
                        #below-right    
                        if j<=sizeRow-2 and k<=sizeColumn-2 and RasterPP[0,j+1,k+1]==0 and RasterPP[1,j+1,k+1]==1:
                            RasterPP[0,j+1,k+1]=1
                                                                                          
            #condition that blocks the while
            N=np.count_nonzero(RasterPP[0])
       
            
            self.Result_matrix=RasterPP[0]
            